// DO NOT EDIT. Automagically generated by the configure script.
// Will be removed by  make clean_all

	AddCommand(new AddComponentCommand);
	AddCommand(new BackwardStepCommand);
	AddCommand(new CloseCommand);
	AddCommand(new ContinueBackwardsCommand);
	AddCommand(new ContinueCommand);
	AddCommand(new CopyComponentCommand);
	AddCommand(new HelpCommand);
	AddCommand(new ListComponentsCommand);
	AddCommand(new LoadCommand);
	AddCommand(new MoveComponentCommand);
	AddCommand(new PauseCommand);
	AddCommand(new QuitCommand);
	AddCommand(new RemoveComponentCommand);
	AddCommand(new ResetCommand);
	AddCommand(new SaveCommand);
	AddCommand(new StatusCommand);
	AddCommand(new StepCommand);
	AddCommand(new VersionCommand);
