// DO NOT EDIT. Automagically generated by the configure script.
// Will be removed by  make clean_all

	{ "cache", CacheComponent::Create, CacheComponent::GetAttribute },
	{ "dummy", DummyComponent::Create, DummyComponent::GetAttribute },
	{ "m88k_cpu", M88K_CPUComponent::Create, M88K_CPUComponent::GetAttribute },
	{ "mips_cpu", MIPS_CPUComponent::Create, MIPS_CPUComponent::GetAttribute },
	{ "mvme187", MVME187Machine::Create, MVME187Machine::GetAttribute },
	{ "machine", MachineComponent::Create, MachineComponent::GetAttribute },
	{ "mainbus", MainbusComponent::Create, MainbusComponent::GetAttribute },
	{ "ram", RAMComponent::Create, RAMComponent::GetAttribute },
	{ "sgi_ip30", SGI_IP30_Machine::Create, SGI_IP30_Machine::GetAttribute },
	{ "sgi_ip32", SGI_IP32_Machine::Create, SGI_IP32_Machine::GetAttribute },
	{ "testm88k", TestM88KMachine::Create, TestM88KMachine::GetAttribute },
	{ "testmips", TestMIPSMachine::Create, TestMIPSMachine::GetAttribute },
