// DO NOT EDIT. Automagically generated by the configure script.
// Will be removed by  make clean_all

#include "components/CacheComponent.h"
#include "components/DummyComponent.h"
#include "components/M88K_CPUComponent.h"
#include "components/MIPS_CPUComponent.h"
#include "components/MVME187Machine.h"
#include "components/MachineComponent.h"
#include "components/MainbusComponent.h"
#include "components/RAMComponent.h"
#include "components/SGI_IP30_Machine.h"
#include "components/SGI_IP32_Machine.h"
#include "components/TestM88KMachine.h"
#include "components/TestMIPSMachine.h"
